// examples/react-demo/src/components/ControlPanel.tsx
import React from 'react'
import type { SelectionTypeConfig } from 'range-kit-react'
import type { TranslationMessages } from '../../../common/i18n'
import './ControlPanel.css'

interface ControlPanelProps {
  isInitialized: boolean
  currentSelections: any[]
  availableTypes: SelectionTypeConfig[]
  getTypeConfig: (type: string) => SelectionTypeConfig | undefined
  selectedSelectionType: string
  interactionMode: string
  t: TranslationMessages
  onLoadMockData: () => void
  onRestoreAllSelections: () => void
  onClearHighlights: () => void
  onPrintData: () => void
  onSelectionTypeChange: (type: string) => void
  onInteractionModeChange: (mode: string) => void
}

export const ControlPanel: React.FC<ControlPanelProps> = ({
  isInitialized,
  currentSelections,
  availableTypes,
  getTypeConfig,
  selectedSelectionType,
  interactionMode,
  t,
  onLoadMockData,
  onRestoreAllSelections,
  onClearHighlights,
  onPrintData,
  onSelectionTypeChange,
  onInteractionModeChange
}) => {
  return (
    <section className="control-panel">
      <div className="panel-header">
        <h2 className="panel-title">{t.controlPanel.title}</h2>
        <div className="selection-count">
          {t.controlPanel.savedSelections}: <span className="count-badge">{currentSelections.length}</span>
        </div>
      </div>

      <div className="control-grid">
        {/* Selection Type */}
        <div className="control-group">
          <h3 className="group-title">{t.controlPanel.selectionType}</h3>

          {/* Type Selector */}
          <div className="type-selector">
            <label className="type-label">{t.controlPanel.selectTypeHint}</label>
            <select 
              value={selectedSelectionType} 
              onChange={(e) => onSelectionTypeChange(e.target.value)}
              className="type-select"
            >
              {availableTypes.map(typeConfig => (
                <option key={typeConfig.type} value={typeConfig.type}>
                  {typeConfig.icon} {typeConfig.label}
                </option>
              ))}
            </select>
            <div className={`type-preview type-${selectedSelectionType}`}>
              {getTypeConfig(selectedSelectionType)?.description || t.controlPanel.defaultStylePreview}
            </div>
          </div>
        </div>

        {/* Interaction Mode */}
        <div className="control-group">
          <h3 className="group-title">{t.controlPanel.interactionMode}</h3>
          <div className="interaction-selector">
            <label className="type-label">{t.controlPanel.triggerActionHint}</label>
            <select 
              value={interactionMode} 
              onChange={(e) => onInteractionModeChange(e.target.value)}
              className="type-select"
            >
              <option value="click">{t.interactionModes.click}</option>
              <option value="hover">{t.interactionModes.hover}</option>
              <option value="dblclick">{t.interactionModes.dblclick}</option>
              <option value="contextmenu">{t.interactionModes.contextmenu}</option>
            </select>
          </div>
        </div>

        {/* Batch Operations */}
        <div className="control-group">
          <h3 className="group-title">{t.controlPanel.batchOperations}</h3>
          <div className="button-group">
            <button
              onClick={onLoadMockData}
              disabled={!isInitialized}
              className="btn btn-primary"
            >
              <span className="btn-icon">📥</span>
              {t.controlPanel.loadPresetData}
            </button>
            <button
              onClick={onRestoreAllSelections}
              disabled={!isInitialized || currentSelections.length === 0}
              className="btn btn-success"
            >
              <span className="btn-icon">🔄</span>
              {t.controlPanel.restoreAllSelections}
            </button>
            <button
              onClick={onClearHighlights}
              disabled={!isInitialized}
              className="btn btn-outline"
            >
              <span className="btn-icon">🧹</span>
              {t.controlPanel.clearAllHighlights}
            </button>
            <button
              onClick={onPrintData}
              disabled={!isInitialized || currentSelections.length === 0}
              className="btn btn-outline"
            >
              <span className="btn-icon">🖨️</span>
              {t.controlPanel.printData}
            </button>
          </div>
        </div>
      </div>
    </section>
  )
}

// backup/range-sdk/examples/vue-demo/src/selection/components/control-panel.vue
<template>
  <section class="control-panel">
    <div class="panel-header">
      <h2 class="panel-title">功能控制面板</h2>
      <div class="selection-count">
        已保存选区: <span class="count-badge">{{ currentSelections.length }}</span>
      </div>
    </div>

    <div class="control-grid">
      <!-- 选区操作 -->
      <div class="control-group">
        <h3 class="group-title">选区操作</h3>

        <!-- 类型选择器 -->
        <div class="type-selector">
          <label class="type-label">选区类型:</label>
          <select v-model="selectedSelectionType" class="type-select">
            <option
              v-for="typeConfig in availableTypes"
              :key="typeConfig.type"
              :value="typeConfig.type"
            >
              {{ typeConfig.icon }} {{ typeConfig.label }}
            </option>
          </select>
          <div class="type-preview" :class="`type-${selectedSelectionType}`">
            {{ getTypeConfig(selectedSelectionType)?.description || '默认样式预览' }}
          </div>
        </div>

        <div class="button-group">
          <button
            @click="$emit('save-selection')"
            :disabled="!isInitialized || isLoading"
            class="btn btn-primary"
          >
            <span class="btn-icon">💾</span>
            保存当前选区
          </button>
          <button
            @click="$emit('clear-highlights')"
            :disabled="!isInitialized"
            class="btn btn-outline"
          >
            <span class="btn-icon">🧹</span>
            清除所有高亮
          </button>
        </div>
      </div>

      <!-- 批量操作 -->
      <div class="control-group">
        <h3 class="group-title">批量操作</h3>
        <div class="button-group">
          <button
            @click="$emit('restore-all-selections')"
            :disabled="!isInitialized || currentSelections.length === 0"
            class="btn btn-success"
          >
            <span class="btn-icon">🔄</span>
            恢复所有选区
          </button>
          <button
            @click="$emit('clear-all')"
            :disabled="!isInitialized || currentSelections.length === 0"
            class="btn btn-danger"
          >
            <span class="btn-icon">🗑️</span>
            清空所有数据
          </button>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup>
import { computed } from 'vue'

// 定义组件属性
const props = defineProps({
  // SDK初始化状态
  isInitialized: {
    type: Boolean,
    default: false
  },
  // 加载状态
  isLoading: {
    type: Boolean,
    default: false
  },
  // 当前选区列表
  currentSelections: {
    type: Array,
    default: () => []
  },
  // 可用的选区类型
  availableTypes: {
    type: Array,
    default: () => []
  },
  // 获取类型配置函数
  getTypeConfig: {
    type: Function,
    required: true
  },
  // 当前选择的选区类型
  selectedSelectionType: {
    type: String,
    default: 'default'
  }
})

// 定义事件
const emit = defineEmits([
  'save-selection',
  'clear-highlights',
  'restore-all-selections',
  'clear-all',
  'update:selectedSelectionType'
])

// 当前选择的选区类型（使用 computed 实现 v-model）
const selectedSelectionType = computed({
  get: () => props.selectedSelectionType,
  set: (value) => emit('update:selectedSelectionType', value)
})
</script>
